### PR TITLE
Update code from test-construct 1.2.0 release

### PR DESCRIPTION
**Pull request by bf4**
More or less what I did

``` sh
git clone devver/construct
gem fetch test-contstruct
gem unpack test-construct
cd construct
cp -Rp ../test-contruct-1.2.0.gem/* .
git checkout -b test-construct
git commit -am 'Update code from rubygem'
```

### CODE REVIEW

**Comment by avdi** [comment]
This seems like a no-brainer -- @bhb, @danmayer any issues merging this?

**Comment by bf4** [comment]
BTW, if you intend to re-maintain the repo here, please enable issues!

**Comment by danmayer** [comment]
No issues from me I still like and use construct as well. I am away from a
computer but could merge and turn on issues tomorrow. Do we want to
maintain here or we could move it under the metric_fu org

**Comment by bhb** [comment]
I'm confused as to how the published gem is out of sync, but whatever. I'm happy to revive this, but I'll do it back under my account. I don't really want to keeping things in the @devver account. @avdi @danmayer Cool?

**Comment by avdi** [comment]
Fine by me!

On Mon, Nov 25, 2013 at 10:51 PM, Ben Brinckerhoff <notifications@github.com

> wrote:
> 
> I'm confused as to how the published gem is out of sync, but whatever. I'm
> happy to revive this, but I'll do it back under my account. I don't really
> want to keeping things in the @devver https://github.com/devveraccount.
> @avdi https://github.com/avdi @danmayer https://github.com/danmayerCool?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/devver/construct/pull/2#issuecomment-29265693
> .

## 

Avdi Grimm
http://avdi.org

I only check email twice a day. to reach me sooner, go to
http://awayfind.com/avdi

**Comment by bf4** [comment]
So, I'll add you all at metricfu/construct and whoever controls the devver rubygems account (I think @danmayer) should add some more owners :)

**Comment by bf4** [comment]
Oops, @bhb totally misread that. Back at your account :)

**Comment by danmayer** [comment]
Bens account works for me. Agree dont want anything under the devver
account. I am also cool with it under metric_fu, either way.

**Comment by danmayer** [comment]
So wish we could have just published it as contract on ruby gems. I guess when we published it we never updated the main repo. Thanks for fixing the mismatch up @bf4

**Comment by bf4** [comment]
Well, whatever you guys decide, Make sure you update the repo to reference the new location, as e.g. @davetron5000's book points here

**Comment by bhb** [comment]
@bf4 I'm looking into it, but my current plan is to switch to a new gem name as the spiritual successor and just redirect everything there.

**Comment by avdi** [comment]
Why the new name?

On Tue, Nov 26, 2013 at 9:37 PM, Ben Brinckerhoff
notifications@github.comwrote:

> @bf4 https://github.com/bf4 I'm looking into it, but my current plan is
> to switch to a new gem name as the spiritual successor and just redirect
> everything there.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/devver/construct/pull/2#issuecomment-29355825
> .

## 

Avdi Grimm
http://avdi.org

I only check email twice a day. to reach me sooner, go to
http://awayfind.com/avdi

**Comment by bhb** [comment]
@avdi I really like the name. Unfortunately, "construct" is already a [different gem](http://rubygems.org/search?utf8=%E2%9C%93&query=construct). The current gem name "test-construct" violates [gem naming best practices](http://guides.rubygems.org/name-your-gem/). Not only does the gem name not match the actual classes, it also misleadingly implies that the classes will be named `Test::Construct` (which itself implies some connection to `Test::Unit`). Gems that make me guess how to require and/or call them are a pet peeve of mine.

In light of that, my current plan is to just make a new gem named "test_construct". The module name will be `TestConstruct`. It's not as nice as the old name, but then again, the old name was never fully the "real" name anyway.

I'm interested in your thoughts on this.

**Comment by avdi** [comment]
OK, that makes sense. It's probably better than my plan of abducting Kyle
Kingsbury and showing him Miley Cyrus until he agrees to give us the
"construct" gem name.

On Tue, Nov 26, 2013 at 11:54 PM, Ben Brinckerhoff <notifications@github.com

> wrote:
> 
> @avdi https://github.com/avdi I really like the name. Unfortunately,
> "construct" is already a different gemhttp://rubygems.org/search?utf8=%E2%9C%93&query=construct.
> The current gem name "test-construct" violates gem naming best practiceshttp://guides.rubygems.org/name-your-gem/.
> Not only does the gem name not match the actual classes, it also
> misleadingly implies that the classes will be named Test::Construct(which itself implies some connection to
> Test::Unit). Gems that make me guess how to require and/or call them are
> a pet peeve of mine.
> 
> In light of that, my current plan is to just make a new gem named
> "test_construct". The module name will be TestConstruct. It's not as nice
> as the old name, but then again, the old name was never fully the "real"
> name anyway.
> 
> I'm interested in your thoughts on this.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/devver/construct/pull/2#issuecomment-29360216
> .

## 

Avdi Grimm
http://avdi.org

I only check email twice a day. to reach me sooner, go to
http://awayfind.com/avdi

**Comment by bhb** [comment]
My plan is simpler, but not necessarily better.

**Comment by avdi** [comment]
That was supposed to read "Miley Cyrus videos". Let the record show that I
am not in possession of a Miley Cyrus.

**Comment by bf4** [comment]
Now if only there were a miley cyrus emoji...

**Comment by bhb** [comment]
@bf4 @davetron5000 OK, the new repo is [here](https://github.com/bhb/test_construct), with Issues enabled. I've added a deprecation warning to the README.

**Comment by bf4** [comment]
Great!

**Comment by bf4** [comment]
@bhb you can also update the repo title/link with someone like [what I did when roodi was revived](https://github.com/metricfu/roodi)

**Comment by bhb** [comment]
@bf4 Yeah, that would be a good idea, except none of us can remember the password for the "devver" account. Fail.

**Comment by bhb** [comment]
Oh snap, just figured it out. Done and done.

**Comment by bf4** [comment]
@bhb Now you just need to release a 'please update' gem :)

I released a [3.0.0](http://rubygems.org/gems/metric_fu-roodi/versions/3.0.0) for metric_fu-roodi that tells you to upgrade.  Try it ;)

**Comment by bhb** [comment]
Good idea. Done!

**Pull request merged**
