### PR TITLE
Removes .devver/devver_opts.yml from .gemspec

### PR DESCRIPTION
**Pull request by ghost**
You forgot to remove the file reference from the .gemspec. Bundler is complaining.

### CODE REVIEW

**Comment by danmayer** [comment]
Thanks this is old and outdated as a file now anyways.

**Comment by ghost** [comment]
I noticed it hasn't been updated for a while. Still works thou, and it's very useful for unit testing. Way better than mocking the file system IMHO.

Do you have a more recent version somewhere?

**Comment by danmayer** [comment]
Yeah we like it better than mock/stubbing out the whole file system. Unfortunately, I don't think any of the three original authors are working with this gem at the moment. So it hasn't been updated for awhile. I doubt any of us are planning to contribute much to it anytime soon. If you have any ideas or fixes feel free to send patches our way and we can get them in.

Last I used it the library was still working fine and doing everything I needed from it.

**Comment by ghost** [comment]
Yeah it does work fine, just that glitch with bundler. Thanks.

**Comment by avdi** [comment]
I still haul construct out from time to time. It does one thing and it does it well!

**Pull request merged**
